Create .entangle_profile
zlounes/cosmos-autostaking pull request #8
Opened 2023-10-02 13:03 UTC by infiniti8

2024-05-31 13:29 UTC, zakarialounes requested changes

2024-05-31 13:29 UTC, zakarialounes commented on profiles/.entangle_profile
> +# Example: VALIDATOR="evmosvaloper19edzsptn6t0v7clgyt7v0xs4t6ucw5nf5un6gh"
please update for entangle

2024-05-31 13:29 UTC, zakarialounes commented on profiles/.entangle_profile
> +# Example: /root/.entangle
Please remove this line

2024-05-31 13:29 UTC, zakarialounes commented on profiles/.entangle_profile
> +NODE_HOME=""
NODE_HOME="$HOME/.entangle"

2024-05-31 13:29 UTC, zakarialounes commented on profiles/.entangle_profile
> +BINARY=""
set a value like `BINARY="$HOME/go/bin/bitsongcli"`

2024-05-31 13:35 UTC, zakarialounes requested changes

2024-05-31 13:35 UTC, zakarialounes commented on profiles/.entangle_profile
> +#SDETAILS="--chain-id ${CHAIN_ID} --node tcp://${NODE_IP}:${NODE_PORT} --home ${NODE_HOME}"
remove this line

2024-05-31 13:35 UTC, zakarialounes commented on profiles/.entangle_profile
> +#DETAILS="${SDETAILS} --keyring-backend ${KEYRING_BACKEND}"
uncomment this line

2024-05-31 13:35 UTC, zakarialounes commented on profiles/.entangle_profile
> +DETAILS="${SDETAILS}"
remove this line

2024-06-03 06:53 UTC, infiniti8 commented
done, ty

2024-06-03 07:00 UTC, closed without merging